### ISSUE TITLE
SPID 2.0 Bugs With Distribution

### ISSUE THREAD

**Issue by GELUXRUM** [powerof3/SPID-F4#1]
While making patches, me and others found 2 different cases of distribution not working properly:

1) Spells do not get distributed at all to the NPC Race and the log output comes out as "added to 0/xxxxx NPCs". This happened with [https://www.nexusmods.com/fallout4/mods/57413](url) and [https://www.nexusmods.com/fallout4/mods/57181](url) for a few of the races: Exploders, Shamblers, PA Shamblers, Spitters and Tanks.
The FallEvil Dogs, however, work with SPID 1.1. Untested for FGEP.

2) Spells do not get distributed to the NPC if they spawn naturally. Spawning them manually via FormID through console works fine and the spell gets applied. The only known mod that this happens to is [https://www.nexusmods.com/fallout4/mods/49680](url).
Both SPID 2.0 and 1.1 have the logs show that the Spell was added to all 9 NPCs, but even with 1.1 the Spell doesn't get added on natural spawning.
Adding the Spell via xEdit works fine.

**Comment by alandtse** [comment]
I don't think anyone will work on older versions of SPID. It may be worth checking of 3.0.0 has this. That was basically bringing it up to feature parity with Skyrim. I also have a NG build via #2. I'm not sure if po3 will take it or just keep them separate.
